name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose --version

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for containers to be healthy
        run: |
          docker-compose -f docker-compose.ci.yml ps
          docker-compose -f docker-compose.ci.yml exec -T web sh -c "
            for i in \$(seq 1 30); do
              if pg_isready -h postgres -U \$POSTGRES_USER; then
                echo 'Postgres is ready'
                exit 0
              fi
              echo 'Waiting for postgres...'
              sleep 1
            done
            echo 'Postgres not ready'
            exit 1
          "

      - name: Run tests inside web container
        run: docker-compose -f docker-compose.ci.yml exec -T web poetry run pytest
